---

 - name: Update 
   apt: update_cache=yes	

 - name: Install
   apt: name=nginx state=present
  
 - name: Add  Nginx config
   file: path=/etc/nginx/sites-enebled/default state=absent
 - name: Add Nginx config
   template: src=app-serv.j2 dest=/etc/nginx/sites-available/app-serv
 - name: Add config
   file: src=/etc/nginx/sites-available/app-serv dest=/etc/nginx/sites-enabled/app-serv  state=link
 - name: Create directory
   file: path=/var/www state=directory mode=0755
 - name: create directory
   file: path=/var/www/{{ hostname }} state=directory mode=0755
 - name: restart nginx
   service: name=nginx state=restarted
 - name: upstart nginx
   shell: update-rc.d nginx defaults

  
