---

 - name: Update 
   apt: update_cache=yes	

 - name: Install
   apt: name=nginx state=present
  
 - name: Add  Nginx config
   file: path=/etc/nginx/sites-enebled/default state=absent
 - name: Add Nginx config
   template: src=app-serv.j2 dest=/etc/nginx/sites-available/app-serv
 - name: Add config
   file: src=/etc/nginx/sites-available/app-serv dest=/etc/nginx/sites-enabled/app-serv  state=link
 - name: Create directory
   file: path=/var/www state=directory mode=0755
 - name: create directory
   file: path=/var/www/{{ hostname }} state=directory mode=0755
 - name: restart nginx
   service: name=nginx state=restarted
 - name: upstart nginx
   shell: update-rc.d nginx defaults

 - name: INstall uwsgi
   apt: name=python-pip state=present
 - name: install
   apt: name=uwsgi-plugin-python state=present
 - name: install
   apt: name=python-dev state=present
 - name: install
   pip:  name=uwsgi
 - name: install
   pip: name=Flask
 - name: copy 
   copy: src=py_app.py  dest=/var/www/{{ hostname }}/ owner=root mode=0644

 - name: copy  
   lineinfile: dest=/etc/hosts insertafter="^127.0.0.1" line="127.0.0.1\tapp-serv"

- name: restart nginx
  service: name=nginx state=restarted
 
 - name: run
   shell: uwsgi --socket 127.0.0.1:3031 --wsgi-file /var/www/{{ hostname }}/*py --callable app & 

 
